---
name: 'MicrosoftGraph'
configurationClass:
  name: 'MicrosoftGraphConfiguration'
  package: 'com.exclamationlabs.connid.base.microsoft.graph.configuration'
results: true
security:
  authenticator:
    oauth2ClientCredentials: true
custom:
  items:
    required:
      tenantId:
        type: string
        display: 'Azure Tenant Id'
        help: 'Identifier for Azure AD Tenant'
      enableDebugHttpLogging:
        type: boolean
        display: 'Debug logging details'
        help: 'This option will expand logs to show more details'
    optional:
      forceChangePasswordOnCreate:
        type: boolean
        display: 'Force Password Reset First Sign In'
        help: 'Require that new users change passwords on first sign in.'
        default: 'false'



